services:
  - type: web
    name: poople-solver-api
    env: python
    region: singapore # or oregon, frankfurt, etc.
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
